export { SupplySummaryWidget } from "./supply-summary-widget";
export { SupplyDepletionWidget } from "./supply-depletion-widget";
export { SettingsCompletionWidget } from "./settings-completion-widget";
export { RatioAdviserWidget } from "./ratio-adviser-widget";
export { WelcomeWidget } from "./welcome-widget";
export { TipOfDayWidget } from "./tip-of-day-widget";
export { AppointmentsWidget } from "./appointments-widget";
export { RoutinesWidget } from "@/components/dashboard/widgets/RoutinesWidget";
export { QuickExerciseWidget } from "@/components/dashboard/widgets/QuickExerciseWidget";
